gcc -c analysis.c
gcc -c param.c
gcc -c spec.c
gcc -c pxi16reader.c
gcc -c bangate.c
gcc -c detmap.c
gcc -c gagg.c
gcc -c germanium.c
gcc -c kinmat.c
#gcc -c pol.c
gcc -c main.c
gcc -c write.c
gcc -c gaggpid.c
gcc -c ggmat.c
gcc -c ggmatglobal.c
#gcc -c dco.c
#gcc -c dcokinmat.c
